"""Public API for IFX Registry."""

from ifx_registry.application.contracts import FetchRequest, VersionProbeRequest
from ifx_registry.application.models import (
    DatasetDescription,
    DerivedDatasetDescription,
    DerivedMaterializedDataset,
    ExternalDatasetDescription,
    MaterializedDataset,
)
from ifx_registry.application.ports.source import (
    SourceAdapter,
    SourceFetcher,
    SourceVersionProbe,
)
from ifx_registry.application.use_cases.audit_snapshot_references import (
    AuditDisposition,
    ReferenceAudit,
    RegistryAudit,
)
from ifx_registry.application.use_cases.fetch_source import FetchSource
from ifx_registry.client import (
    DEFAULT_CACHE_DIR,
    DerivedRegistryClient,
    ExternalRegistryClient,
    RegistryAuditClient,
    RegistryClient,
)
from ifx_registry.domain.catalog import (
    PublishedDerivedSnapshot,
    PublishedExternalDatasetVersion,
    PublishedFile,
    PublishedSnapshot,
)
from ifx_registry.domain.errors import (
    CatalogConsistencyError,
    DatasetFileNotFoundError,
    InvalidDatasetIdError,
    InvalidPublicationError,
    InvalidSnapshotIdError,
    MaterializationError,
    MultipleDatasetFilesError,
    RegistryClientConfigurationError,
    RegistryError,
    RegistryUnavailableError,
    SnapshotAlreadyExistsError,
    SnapshotNotFoundError,
    SourceAcquisitionError,
    SourceConfigurationError,
    SourceContractError,
    SourceValidationError,
    VersionMismatchError,
)
from ifx_registry.domain.models import (
    DatasetId,
    DatasetVersion,
    DerivedSnapshot,
    DerivedSnapshotFile,
    ExternalDatasetVersion,
    ProducerIdentity,
    SnapshotFile,
    SnapshotKind,
    SnapshotRef,
    SourceSnapshot,
    SourceVersion,
)

__all__ = [
    "AuditDisposition",
    "DatasetId",
    "DatasetDescription",
    "DatasetVersion",
    "DerivedRegistryClient",
    "DerivedDatasetDescription",
    "DerivedMaterializedDataset",
    "DerivedSnapshot",
    "DerivedSnapshotFile",
    "ExternalDatasetDescription",
    "ExternalDatasetVersion",
    "ExternalRegistryClient",
    "FetchRequest",
    "FetchSource",
    "DatasetFileNotFoundError",
    "CatalogConsistencyError",
    "InvalidDatasetIdError",
    "InvalidPublicationError",
    "InvalidSnapshotIdError",
    "MaterializationError",
    "MultipleDatasetFilesError",
    "MaterializedDataset",
    "PublishedFile",
    "PublishedDerivedSnapshot",
    "PublishedExternalDatasetVersion",
    "PublishedSnapshot",
    "ReferenceAudit",
    "RegistryAudit",
    "RegistryAuditClient",
    "RegistryClient",
    "DEFAULT_CACHE_DIR",
    "RegistryError",
    "RegistryClientConfigurationError",
    "RegistryUnavailableError",
    "ProducerIdentity",
    "SnapshotFile",
    "SnapshotAlreadyExistsError",
    "SnapshotKind",
    "SnapshotNotFoundError",
    "SnapshotRef",
    "SourceAdapter",
    "SourceAcquisitionError",
    "SourceContractError",
    "SourceConfigurationError",
    "SourceFetcher",
    "SourceSnapshot",
    "SourceVersion",
    "SourceVersionProbe",
    "SourceValidationError",
    "VersionMismatchError",
    "VersionProbeRequest",
]
